// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjecpfjvnugyhojasmwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqZWNwZmp2bnVneWhvamFzbXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODY2NzksImV4cCI6MjA2NDI2MjY3OX0.g0TeYLg8z6w_V92DlURZd0xZ6mwIYV2Y8B6Rri1Iwv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);